### ISSUE TITLE
Resource - Config

### ISSUE THREAD

**Issue by NathanBland** [whiteboards/habitus#10]
Call it `config`, call it `settings` either way, here are my suggestions for `front-end` settings. I am making that distinction because i think these kinds of settings _should_ be kept in the `db`. Anything that affects the `api` or what it talks to, should be in a flat file or some kind. My opinion, open to discussion.

Without further ado, the proposed model!

```
title: attr('string'), // this would replace "habitus"
tagline: attr('string'), // this would replace, for example on our "hero" landing "Elegant, minimal, complete."
logo: attr('string'), // this would be the link, or relationship to the file item, that holds the url of the logo
theme: attr('string'), // this will sit at the value "default" for a long, long time.
fileSizeLimit: attr('number'), // size in MB of the largest allowed file the system can handle
enableUserUploads: attr('boolean') //can non admin users upload things?
enableRegistration: attr('boolean'), // allow users to register on their own.
enableBlog: attr('boolean'), //not all sites want a blog.
enableFileUploads: attr('boolean'), // I don't want ANY media (for some reason?)
frontPage: attr('string'), // by default this will be index, and until I figure out how to do some clever things, it would stay this way.
```

I'm sure as we build more features, specifically once we get to plugins, more settings that should be considered global will apply, but for now, this is all I can think of.

Notice that I didn't anything like `dbHost` or anything like that. To me, that config should be done on setup, or migration, and isn't the `ui`'s responsibility to worry about. ;)

**Comment by crodeheaver** [comment]
Those things are fine to me. And I don't think server things should be changed through the UI anyways, unless we find a good reason for it. In which case, they can just edit the server config file or setup environment variables.

**Comment by NathanBland** [comment]
A new value that I just appended to this
`enableBlog: attr('boolean')`

Not all sites want a blog, and..
`enableFileUploads: attr('boolean'),`

Not all sites want to allow uploads.

**Comment by crodeheaver** [comment]
Ya. I had thought about that the other day when I was using a cms at work. Good call.

**Comment by crodeheaver** [comment]
This should be good to go.
